# Generated by Django 5.0.14 on 2025-10-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0002_initial"),
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="owners",
            field=models.ManyToManyField(
                blank=True,
                related_name="owned_restaurants",
                to="userprofile.userprofile",
            ),
        ),
    ]
