# Generated by Django 5.0.14 on 2025-10-13 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0004_category_restaurant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="restaurant",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="restaurants.restaurant",
            ),
            preserve_default=False,
        ),
    ]
