# Generated by Django 5.0.14 on 2025-10-13 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0005_alter_category_restaurant"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table=None,
        ),
    ]
