# Generated by Django 5.0.14 on 2025-10-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0006_alter_category_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
