# Generated by Django 5.0.14 on 2025-10-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0007_alter_menu_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="menu",
            constraint=models.UniqueConstraint(
                fields=("restaurant", "name"), name="unique_menu_per_restaurant"
            ),
        ),
        migrations.AddConstraint(
            model_name="menuitem",
            constraint=models.UniqueConstraint(
                fields=("menu", "name"), name="unique_menu_item_per_menu"
            ),
        ),
        migrations.AddConstraint(
            model_name="menuitemingredient",
            constraint=models.UniqueConstraint(
                fields=("menu_item", "name"), name="unique_ingredient_per_menu_item"
            ),
        ),
    ]
