# Generated by Django 5.0.14 on 2025-10-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "restaurants",
            "0008_alter_menu_name_menu_unique_menu_per_restaurant_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("restaurant", "name"), name="unique_category_per_restaurant"
            ),
        ),
    ]
