# Generated by Django 5.0.14 on 2025-11-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0009_alter_category_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="table_state",
            field=models.CharField(
                choices=[
                    ("OCCUPIED", "Table Occupied"),
                    ("SERVED", "Order Served"),
                    ("EMPTY", "Table Empty"),
                ],
                default="EMPTY",
                max_length=20,
            ),
        ),
    ]
