# Generated by Django 5.0.14 on 2025-11-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0010_table_table_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="customer_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
