# Generated by Django 5.0.14 on 2025-11-13 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0011_table_customer_count"),
        ("userprofile", "0004_alter_userprofile_selected_restaurant"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="waiter",
            field=models.ForeignKey(
                blank=True,
                help_text="Assign waiter if dine-in service was provided.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="waiter_reviews",
                to="userprofile.userprofile",
            ),
        ),
    ]
