# Generated by Django 5.0.14 on 2025-10-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0002_alter_userprofile_restaurant_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="selected_restaurant",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=5, null=True
            ),
        ),
    ]
