# Generated by Django 5.0.14 on 2025-10-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0003_userprofile_selected_restaurant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="selected_restaurant",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
